---
# Lambda School Data Science - Intro to Python  
---
# 05 - Numpy
---



##STOP! BEFORE GOING ANY FURTHER...  


1. Click "File" at the top.
2. Then, "Save a Copy in Drive."
3. Change the file name to "FIRSTNAME_LASTNAME_1_2"  

Now you have a copy of this notebook in your Drive account. This is the copy you'll edit and submit. Be sure to do this for ***every*** assignment!



### Import Numpy as Np

In [0]:
import numpy as np

### Generate random numbers
Create a (5,3) Numpy array of random integer values between 0 and 100.

In [30]:
R = 100.0*np.random.random((5, 3))
print(R)

[[ 6.25455457 25.41780812 89.27100483]
 [49.17993385 34.17210567 87.07351329]
 [12.34624996 50.9845248  57.3659387 ]
 [31.60859237 48.76891157  3.14692149]
 [ 1.25259202 78.36805513 34.02976585]]


### Array practice
Run each of these in their own code cell and comment it accordingly:

*  Return the first row
*  Return the last column
*  Return the third column values from the 4th and 5th rows
*  Multiply every value in the array by 2
*  Divide every value by 3
*  Increase the values in the first row by 12
* Calculate the mean of the first column
* Calculate the median of the array _after_ removing the 2 smallest values in the array
* Calculate the standard deviation of the first 3 rows
* Return values in the second column greater than 25
* Return values in the array under 40

In [31]:
# Return the first row:
R_01 = R[0, :]
print("First row: \n" + str(R_01))

First row: 
[ 6.25455457 25.41780812 89.27100483]


In [32]:
# Return the last column:
R_02 = R[:, -1]
print("Last column: \n" + str(R_02))

Last column: 
[89.27100483 87.07351329 57.3659387   3.14692149 34.02976585]


In [33]:
# Return the third column values from the 4th and 5th rows:
R_03 = R[3:5, 2]
print("3rd column from row 4th & 5th: \n" + str(R_03))

3rd column from row 4th & 5th: 
[ 3.14692149 34.02976585]


In [34]:
# Multiply every value in the array by 2:
R_04 = R*2.0
print("Multiply values in array by 2: \n" + str(R_04))

Multiply values in array by 2: 
[[ 12.50910914  50.83561625 178.54200966]
 [ 98.35986771  68.34421133 174.14702658]
 [ 24.69249991 101.96904961 114.7318774 ]
 [ 63.21718474  97.53782314   6.29384298]
 [  2.50518404 156.73611026  68.05953169]]


In [35]:
# Divide every value by 3:
R_05 = R/3.0
print("Divide values in array by 3: \n" + str(R_05))

Divide values in array by 3: 
[[ 2.08485152  8.47260271 29.75700161]
 [16.39331128 11.39070189 29.02450443]
 [ 4.11541665 16.9948416  19.12197957]
 [10.53619746 16.25630386  1.04897383]
 [ 0.41753067 26.12268504 11.34325528]]


In [36]:
# Increase the values in the first row by 12:
R_06 = R.copy() # Do not affect initial random array.
R_06[0] += 12
print("Add 12 to first row values: \n" + str(R_06))

Add 12 to first row values: 
[[ 18.25455457  37.41780812 101.27100483]
 [ 49.17993385  34.17210567  87.07351329]
 [ 12.34624996  50.9845248   57.3659387 ]
 [ 31.60859237  48.76891157   3.14692149]
 [  1.25259202  78.36805513  34.02976585]]


In [42]:
# Calculate the mean of the 1st column:
R_07 = np.mean(R[:, 0])
print("Calculate mean of 1st column: \n" + str(R_07))

Calculate mean of 1st column: 
20.12838455405289


In [38]:
# Median of the array after removing the 2 smallest values:
R_08a = np.reshape(R.copy(), -1)  # Reshape R into 1D array.
R_08b = sorted(R_08a)[2:]  # Sort from small to large; erase 2 leftmost values.
R_08  = np.median(R_08b)    # Calculate median
print("Array median without 2 smallest values: \n" + str(R_08))

Array median without 2 smallest values: 
48.76891156865254


In [39]:
# Calculate the standard deviation of the first 3 rows:
R_09 = np.std(R[:3, :])
print("Standard deviation of first 3 rows: \n" + str(R_09))

Standard deviation of first 3 rows: 
27.886557217211795


In [40]:
# Return values in the second column greater than 25:
R_10a = R[:, 1]
R_10  = R_10a[R_10a > 25]
print("Values in 2nd column > 25: \n" + str(R_10))

Values in 2nd column > 25: 
[25.41780812 34.17210567 50.9845248  48.76891157 78.36805513]


In [41]:
# Return values in the array under 40:
R_11 = R[R < 40]
print("values in whole array < 40: \n" + str(R_11))

values in whole array < 40: 
[ 6.25455457 25.41780812 34.17210567 12.34624996 31.60859237  3.14692149
  1.25259202 34.02976585]
